format_version: 10
pipelines:
  ci-server:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/Prajaika/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
      secure_variables:
      TF_VAR_vault_token: AES:YV42gYq2yWYCgg9bBS751w==:0J4Y60lLT3HsxDdkAdXTMky20Zle8D6iW9YBArhOCqk=     
    stages:
    - Ansible:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            tasks:
            - exec: {command: ansible-playbook, arguments: [ "-i", "ci-server-internal.Prajaika.online,", "tools.yml", "-e", "tool_name=ci-server", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}
